version: '3.8'
services:
  rest:
    build:
      dockerfile: Dockerfile
      context: valentine-rest-service
      target: development
    volumes:
      - ./valentine-rest-service:/usr/src/rest
      - ./valentine-rest-service/node_modules:/usr/src/rest/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ${DB_URL}
    ports:
      - 8080:3000
    restart: always

  auth:
    build:
      dockerfile: Dockerfile
      context: ./valentine-auth-service
      target: development
    volumes:
      - ./valentine-auth-service:/usr/src/auth
      - ./valentine-auth-service/node_modules:/usr/src/auth/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: ${DB_URL}
      AUTH_LINK: ${AUTH_LINK}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      GRANT_TYPE: ${GRANT_TYPE}
      REDIRECT_URI: ${REDIRECT_URI}
    ports:
      - 8040:3000
    restart: always

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  pg_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - 5440:80
    restart: unless-stopped
